name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # para permitir escritura en README

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update recent activity in README
        uses: jamesgeorge007/github-activity-readme@master
        with:
          GH_USERNAME: Yourchh
          MAX_LINES: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit README update
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Update GitHub activity section"
