name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"   # cada 12 horas en el minuto 0
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update recent activity
        uses: Readme-Workflows/activity@v1
        with:
          GH_USERNAME: Yourchh
          MAX_LINES: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
