name: Actualizar Actividad Reciente del README

on:
  schedule:
    # Se ejecuta cada 6 horas
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Actualizar sección de actividad reciente
        uses: Readme-Workflows/recent-activity@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
