name: Update GitHub Activity

on:
  schedule:
    - cron: "0 */12 * * *"  # Cada 12 horas
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necesario para hacer commits

    steps:
      # Clonar tu repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Actualizar la actividad reciente
      - name: Update GitHub activity in README
        uses: jamesgeorge007/github-activity-readme@master
        with:
          GH_USERNAME: Yourchh
          MAX_LINES: 6
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      # Hacer commit solo si hay cambios
      - name: Commit changes if any
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update GitHub activity section"
          branch: main
          file_pattern: README.md
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      # Opcional: mostrar un mensaje si no hay cambios
      - name: Check for changes
        run: |
          git diff --exit-code || echo "README updated!"
